### PR TITLE
Add --do-not-rmi option to hurl clean

### PR DESCRIPTION
**Pull request by mseshachalam**
This flag avoids removing the docker images

### CODE REVIEW

**Comment by walmon** [comment]
Hi @mseshachalam thanks! This looks fine. I'll test it locally today and publish it. I let you know here

**Comment by diestrin** [comment]
I tried running this with `npm link`, but it is still deleting the chaincode images. @walmon can you confirm the same on your side? I put a breakpoint in the clean handler, but the `noRmi` param seems to be undefined for some reason.

**Comment by mseshachalam** [comment]
@diestrin Please check now. You were correct about the undefined value for flag. Not sure why the flag is undefined when its --no-rmi but works with --do-not-rmi. Please update the shorthand for this flag (-n) to appropriate one.

**Comment by mseshachalam** [comment]
@diestrin --no-rmi is a negate type flag in commander. Fixed the issues. 

the command is now `hurl clean --no-rmi` or `hurl clean -R`

**Comment by diestrin** [comment]
Looks good, thank you!

**Pull request merged**
